name: Run Experiment

on:
  push:
    branches:
      - main

jobs:
  run-experiment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate experiment
        run: |
          cd remvae
          PYTHONPATH=. python generator/generate.py experiments/gru_example/args.json